### ISSUE TITLE
バッファサイズの調整

### ISSUE THREAD

**Issue by ShotaroMatsuya** [ShotaroMatsuya/firelens-fluentbit-refresher#1]
filrens log routerをECS on fargate上にsidecarとして配置するためには、essential: trueとする必要がある。
そのため、firelensコンテナがOOM Killerによってkillされてしまうことにより、ECS task自体が全滅してしまう。
大量のログをさばくためにfirelensのconfにて適切なバッファサイズやflush timeを設定する必要がある

**Comment by mm-sho-matsuya** [comment]
参考リンク
[https://docs.fluentbit.io/manual/administration/buffering-and-storage](https://github.com/mm-engineer/qb-medical_staff-cms/issues/%E3%82%AA%E3%83%95%E3%82%A3%E3%82%B7%E3%83%A3%E3%83%AB)

2. Mem_Buf_Limit
To prevent high memory usage, Fluent Bit has [a setting called Mem_Buf_Limit](https://docs.fluentbit.io/manual/administration/backpressure) which can be set on each input definition.

This setting restricts the total amount of memory that the input can use- Fluent BIt considers inputs to "own" the buffers for logs, so this setting controls the size of the memory buffer that each input can use. Therefore, to fully restrict the memory usage fully for Fluent Bit you must set Mem_Buf_Limit on every input definition. Though in practice, if you set Mem_Buf_Limit on only the inputs that experience the highest throughput of logs this should mostly contain its total memory usage.

This setting only restricts the input memory, not the memory used by filters and outputs. However, in practice, if the input can not buffer more than a certain amount of logs, this effectively controls the memory usage of all of the other plugins in the Fluent Bit pipeline, since inputs control log ingestion. AWS FireLens team has found that in general, the total memory usage of Fluent Bit will stay below two times the sum of the Mem_Buf_Limit for each input. That is:

Total Memory Usage <= 2 * SUM(Each input Mem_Buf_Limit)
Thus, if you give Fluent Bit a 200 MB memory limit in your container definition, then the sum of all Mem_Buf_Limit should not exceed 100 MB.

Of course, there are downsides to Mem_Buf_Limit. If an input runs out of memory buffer, it stop ingesting logs and emit messages like the following:

[input] forward.1 paused (mem buf overlimit)
This means you will lose logs. And other components may experience errors, for example, if you use the [log4j TCP appender to write logs to Fluent Bit](https://github.com/aws-samples/amazon-ecs-firelens-examples/tree/mainline/examples/fluent-bit/ecs-log-collection), log4j will experience a connection failure.

Unfortunately, in FireLens, the [log inputs for stdout/stderr error logs from your application container(s) is auto-generated by ECS](https://aws.amazon.com/blogs/containers/under-the-hood-firelens-for-amazon-ecs-tasks/), and has no Mem_Buf_Limit set. Thus, you must use the workaround in this blog to set it: [How to set Fluentd and Fluent Bit input parameters in FireLens](https://aws.amazon.com/blogs/containers/how-to-set-fluentd-and-fluent-bit-input-parameters-in-firelens/).

3. Filesystem buffering
You can also tell the input to buffer on the filesystem. This can be used with our without Mem_Buf_Limit, but they are best used together.

By default, when you enable filesystem buffering, Fluent Bit buffers all chunks BOTH in memory and on the filesystem. The number of chunks that are "up" in memory can be restricted with the storage.max_chunks_up setting.

Please read the [official Fluent Bit documentation](https://docs.fluentbit.io/manual/administration/buffering-and-storage) to understand the filesystem buffering settings. And remember that AWS FireLens team recommends always setting Mem_Buf_Limit when you enable filesystem buffering.

Unfortunately, as noted in the documentation link above, the filesystem buffering must be enabled on the input definition, therefore, for the [stdout/stderr input generated by FireLens](https://aws.amazon.com/blogs/containers/under-the-hood-firelens-for-amazon-ecs-tasks/), the same workaround is required: [How to set Fluentd and Fluent Bit input parameters in FireLens](https://aws.amazon.com/blogs/containers/how-to-set-fluentd-and-fluent-bit-input-parameters-in-firelens/).
